### ISSUE TITLE
pull-request auth fails returning 401

### ISSUE THREAD

**Issue by ahmedelgabri** [github/hub#1021]
```shell
$ hub pull-request 
Error getting current user: Unauthorized (HTTP 401)
Bad credentials

$ hub --version
git version 2.6.2
hub version 2.2.2
```

In my `~/.config/hub` this is what I have

```yaml
github.com:
- user: ahmedelgabri
  oauth_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  protocol: https
```

According to the [`2.2.2 changelog`](https://github.com/github/hub/releases/tag/v2.2.2) `hub` should use `$GITHUB_TOKEN` instead of `~/.config/hub`. I tried this and it didn't work, I also tried to remove the token form the config so it picks up `$GITHUB_TOKEN` only and it didn't work too.
