### ISSUE TITLE
Hub complains of commits not yet pushed but there are none

### ISSUE THREAD

**Issue by edrpls** [github/hub#1130]
Hi, I'm not really sure if this is a bug or I am missing something here, while trying to open a pull request to enterprise github with `git pull-request` from the develop branch, but I get the following message:

`Aborted: 89 commits are not yet pushed to origin/develop`

I'm 100% sure this is wrong since everything has been pushed (git push outputs "Everything up-to-date"),

I get the same result with `git pull-request -b origin/develop`

Am I missing something?

The contents of ~/.config/hub:

```
git.removed.removed.com:
- user: edrpls
  oauth_token: REMOVED_TOKEN
  protocol: https
```

Thanks!
