### ISSUE TITLE
Change credentials using GITHUB_USER env var

### ISSUE THREAD

**Issue by bentinata** [github/hub#2460]
**The problem I'm trying to solve:**
Changing credentials by setting the `GITHUB_USER` environment variable.

**How I imagine hub could expose this functionality:**
If I have `~/.config/hub` filled with this:
```
github.com:
- user: bentinata
  oauth_token: 8d95386c5bd67844cac087ce5b5927728d11187f
- user: bentinatabot
  oauth_token: 9b647d0f869487781b5de8fe122b2916142b70ec
```

Using `GITHUB_USER=bentinatabot hub create` or `GITHUB_USER=bentinatabot hub api` would run the command using `bentinatabot` token and username.
