### ISSUE TITLE
Document hub config file format

### ISSUE THREAD

**Issue by gibfahn** [github/hub#2526]
It would be nice to document the hub config file format somewhere.

When I set this up I had to read through the hub source to work out what the config should look like, and was unable to get toml to work.

For example my current config looks like this:

```yaml
github.com:
- user: <username>
  oauth_token: "<token>"
  protocol: https

# GHE
github.<myorg>.com:
- user: <username>
  oauth_token: "<token>"
  protocol: https
```

I'd be happy to raise a PR, but I'm not sure where the best place would be, maybe in the README? In `man hub`?
