### ISSUE TITLE
value from the inputs are not passing to the called workflow when using Reusable workflow scenario

### ISSUE THREAD

**Issue by prasoon-pxc** [github/hub#3100]
I am using a Reusable workflow with one input variable , while I am calling this workflow from another workflow input value is not getting passed.

---
CALLED_WORKFLOW

```
name: called workflow

on:
  workflow_call:
    inputs:
      custom_chart_name:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        run: |
          export CUSIN="${{ github.event.inputs.custom_chart_name }}"
          echo $CUSIN
```

---

CALLER_WORKFLOW

```
name: caller workflow

on:
  push:
   branches:
    - main

jobs:
  helm:
    uses: ./.github/workflows/test.yaml
    with:
      custom_chart_name: "global-monitoring"

```
---
not getting value of `$CUSIN` in output
