### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by afeld** [github/hub#390]
When I'm working on a new project, I find myself renaming it after I realize what it's really about.  This is a multi-step manual process:
1. Navigate to the project settings page
2. Type in the new name
3. Copy the new Git URL
4. `git remote set-url origin ...`

Would be great to have this as a one-liner (with a confirmation) using hub.  My proposal:

```
$ hub rename new-repo
Are you sure you want to rename this repository [Ny]? y
Your repository can now be found at https://github.com/USER/new-repo.
```

**Comment by mislav** [comment]
After some consideration, I have decided that—for now—this is best implemented in user scripts, rather than maintained in hub core. Now that there is a new `hub api` command, I will close this feature request and leave implementing this as an exercise to the reader. https://github.com/github/hub/releases/tag/v2.8.3 https://github.com/github/hub/pull/2016

For example:
```sh
hub api -XPATCH repos/{owner}/{repo} -f name=my-new-name
# (parse out the new URL from server response)
git remote set-url origin <NEW-URL>
```

Thank you for suggesting!

**Comment by gko** [comment]
or with an alias
```TOML
[alias]
  set-url = remote set-url origin
  rename-repo = "!f() { hub api --flat -XPATCH repos/{owner}/{repo} -f name=$1 | grep .ssh_url | awk '/.ssh_url/ {print $2}' | xargs git set-url; }; f"
```

so that you run `git rename-repo <something>`

P.S. thank you to @mislav and GitHub for `hub api`. It's amazing!
